// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findOrCreate = `-- name: FindOrCreate :one
INSERT INTO users (email , provider, phone, name, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT(email)
DO UPDATE SET
   phone = EXCLUDED.phone,
   provider = EXCLUDED.provider,
   updated_at = now()
RETURNING id , name, phone, provider , role, password_hash
`

type FindOrCreateParams struct {
	Email        string
	Provider     NullProvider
	Phone        pgtype.Text
	Name         string
	PasswordHash pgtype.Text
}

type FindOrCreateRow struct {
	ID           pgtype.UUID
	Name         string
	Phone        pgtype.Text
	Provider     NullProvider
	Role         UserRole
	PasswordHash pgtype.Text
}

func (q *Queries) FindOrCreate(ctx context.Context, arg FindOrCreateParams) (FindOrCreateRow, error) {
	row := q.db.QueryRow(ctx, findOrCreate,
		arg.Email,
		arg.Provider,
		arg.Phone,
		arg.Name,
		arg.PasswordHash,
	)
	var i FindOrCreateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Provider,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}
