// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DriverStatus string

const (
	DriverStatusONLINE  DriverStatus = "ONLINE"
	DriverStatusOFFLINE DriverStatus = "OFFLINE"
	DriverStatusBUSY    DriverStatus = "BUSY"
)

func (e *DriverStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DriverStatus(s)
	case string:
		*e = DriverStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DriverStatus: %T", src)
	}
	return nil
}

type NullDriverStatus struct {
	DriverStatus DriverStatus
	Valid        bool // Valid is true if DriverStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDriverStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DriverStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DriverStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDriverStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DriverStatus), nil
}

type Provider string

const (
	ProviderGOOGLE   Provider = "GOOGLE"
	ProviderAPPLE    Provider = "APPLE"
	ProviderPASSWORD Provider = "PASSWORD"
)

func (e *Provider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Provider(s)
	case string:
		*e = Provider(s)
	default:
		return fmt.Errorf("unsupported scan type for Provider: %T", src)
	}
	return nil
}

type NullProvider struct {
	Provider Provider
	Valid    bool // Valid is true if Provider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvider) Scan(value interface{}) error {
	if value == nil {
		ns.Provider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Provider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Provider), nil
}

type RideRequestStatus string

const (
	RideRequestStatusSEARCHING RideRequestStatus = "SEARCHING"
	RideRequestStatusMATCHED   RideRequestStatus = "MATCHED"
	RideRequestStatusCANCELLED RideRequestStatus = "CANCELLED"
	RideRequestStatusCOMPLETED RideRequestStatus = "COMPLETED"
)

func (e *RideRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RideRequestStatus(s)
	case string:
		*e = RideRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RideRequestStatus: %T", src)
	}
	return nil
}

type NullRideRequestStatus struct {
	RideRequestStatus RideRequestStatus
	Valid             bool // Valid is true if RideRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRideRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RideRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RideRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRideRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RideRequestStatus), nil
}

type TripStatus string

const (
	TripStatusCOMPLETED TripStatus = "COMPLETED"
	TripStatusONGOING   TripStatus = "ONGOING"
	TripStatusREJECTED  TripStatus = "REJECTED"
)

func (e *TripStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripStatus(s)
	case string:
		*e = TripStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TripStatus: %T", src)
	}
	return nil
}

type NullTripStatus struct {
	TripStatus TripStatus
	Valid      bool // Valid is true if TripStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TripStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripStatus), nil
}

type UserRole string

const (
	UserRoleDRIVER UserRole = "DRIVER"
	UserRoleUSER   UserRole = "USER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VehicleType string

const (
	VehicleTypeSEDAN VehicleType = "SEDAN"
	VehicleTypeSUV   VehicleType = "SUV"
)

func (e *VehicleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleType(s)
	case string:
		*e = VehicleType(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleType: %T", src)
	}
	return nil
}

type NullVehicleType struct {
	VehicleType VehicleType
	Valid       bool // Valid is true if VehicleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleType) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleType), nil
}

type DriverLocation struct {
	DriverID  pgtype.UUID
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
}

type DriverProfile struct {
	UserID        pgtype.UUID
	LicenseNumber pgtype.Int4
	Status        NullDriverStatus
	Rating        pgtype.Float8
	UpdatedAt     pgtype.Timestamptz
}

type RideRequest struct {
	ID              pgtype.UUID
	RiderID         pgtype.UUID
	PickupLat       pgtype.Float8
	PickupLong      pgtype.Float8
	DestinationLat  pgtype.Float8
	DestinationLong pgtype.Float8
	Status          NullRideRequestStatus
	CreatedAt       pgtype.Timestamptz
}

type RiderProfile struct {
	UserID pgtype.UUID
	Rating pgtype.Float8
}

type Trip struct {
	ID            pgtype.UUID
	RideRequestID pgtype.UUID
	DriverID      pgtype.UUID
	Status        NullTripStatus
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Role         UserRole
	Email        string
	Phone        pgtype.Text
	PasswordHash pgtype.Text
	Provider     NullProvider
	CreatedAt    pgtype.Timestamptz
}

type Vehicle struct {
	ID          pgtype.UUID
	DriverID    pgtype.UUID
	Model       pgtype.Text
	PlateNumber pgtype.Text
	Type        NullVehicleType
}
