// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
)

const getAllUser = `-- name: GetAllUser :many
SELECT id, name, phone from riders
`

func (q *Queries) GetAllUser(ctx context.Context) ([]Rider, error) {
	rows, err := q.db.Query(ctx, getAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rider
	for rows.Next() {
		var i Rider
		if err := rows.Scan(&i.ID, &i.Name, &i.Phone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
