package service

import (
	"backend/db"
	"backend/internal/repository"
	"context"

	"github.com/gofrs/uuid"
)

type DriverService struct {
	DriverRepository *repository.DriverRepository
}

func NewDriverService(DriverRepository *repository.DriverRepository) *DriverService {
	return &DriverService{
		DriverRepository: DriverRepository,
	}
}

func (s *DriverService) GetDriverData(ctx context.Context, id uuid.UUID) ([]db.User, error) {
	// Call the type-safe method generated by sqlc automatically!
	driver, err := s.DriverRepository.GetAllUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return driver, nil
}
